version: "3.3"

services:
  app:
    container_name: "wellmate_api"
    image: "wellmate_api:latest"
    deploy:
      restart_policy:
        condition: any
    env_file:
      - ".env"
    network_mode: "bridge"
    entrypoint: "/app/entrypoint.sh"
    ports:
      - "8001:8000"
    build:
      context: .
      dockerfile: "Dockerfile"
